//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAdmin
    {
        public int idAdmin { get; set; }
        public string codeAdmin { get; set; }
        public string nameAdmin { get; set; }
        public string phone { get; set; }
        public string userName { get; set; }
        public string passWord { get; set; }
        public string access { get; set; }
    }
}
